### ISSUE TITLE
Package shouldn't remove the ImageSharp.Web PhysicalFileSystemProvider

### ISSUE THREAD

**Issue by Jeavon** [umbraco/Umbraco.StorageProviders#16] opened 2021-09-29 16:24 UTC
When this package is installed the default ImageSharp.Web PhysicalFileSystemProvider is removed so you can't use ImageSharp.Web outside of the /media path.

e.g. /img/logo.png?width=100 works before the package is installed but doesn't after

**Comment by ronaldbarendse** [comment] 2021-09-30 11:52
I can confirm that using `AddAzureBlobMediaFileSystem()` does indeed change this behavior 😢 

The default `PhysicalFileSystemProvider` is registered first, [matches all requests](https://github.com/SixLabors/ImageSharp.Web/blob/97852c1f88c2e9b77ae081265379363cdf8fe5b6/src/ImageSharp.Web/Providers/PhysicalFileSystemProvider.cs#L53) and therefore will [always be the provider used by the `ImageSharpMiddleware`](https://github.com/SixLabors/ImageSharp.Web/blob/97852c1f88c2e9b77ae081265379363cdf8fe5b6/src/ImageSharp.Web/Middleware/ImageSharpMiddleware.cs#L205-L213). This is why it's replaced by using `builder.Services.AddUnique<IImageProvider, AzureBlobFileSystemImageProvider>()`, which only matches the path that's mapped to the blob container.

For now, you can manually re-add the `PhysicalFileSystemProvider` after the `AddAzureBlobMediaFileSystem()` call, so it will not be the first provider and therefore be used for all physical files outside of the configured Azure Blob Storage container media path by using:

```c#
builder.Services.AddSingleton<IImageProvider, PhysicalFileSystemProvider>();
```

Note that any physical files inside the physical media folder will still be served by the static file middleware, but will not be processed by ImageSharp. I think this should be [fixed in ImageSharp](https://github.com/SixLabors/ImageSharp.Web/blob/b37ac7f0299461d2bf873cf6f2329ba079435eec/src/ImageSharp.Web/Middleware/ImageSharpMiddleware.cs#L204-L223), so it first filters all providers using `Match` and then uses the first provider that returns a non-null `IImageResolver`.

**Comment by JimBobSquarePants** [comment] 2021-09-30 12:21
> I think this should be fixed in ImageSharp, so it first filters all providers using Match and then uses the first provider that returns a non-null IImageResolver.

Disagree strongly here. The default provider is specifically designed to be catch all. You should register the providers in the order you want them to run. Adding extra filtering hurts performance.

**Comment by ronaldbarendse** [comment] 2021-10-04 22:06
@JimBobSquarePants Then what's the reason for allowing multiple `IImageProvider`s to be registered? And yes, doing more lookups/filtering might hurt performance, but that shouldn't prevent adding a bit more flexibility to ImageSharp: https://github.com/SixLabors/ImageSharp.Web/pull/185.

ImageSharp already does double filtering, first by using `Match(HttpContext context)` and then `IsValidRequest(HttpContext context)`: if only a single provider is picked by the first, why do you need to check if it's a valid request too?

**Comment by JimBobSquarePants** [comment] 2021-10-04 22:25
ImageSharp.Web (Note name) is flexible enough thank you. It works fine for everyone else including other CMS systems who proactively engaged with me and I have worked closely with. If something doesn’t work your way it doesn’t mean that it doesn’t work.

**Closed** 2021-11-11 12:14 UTC
Labels: bug
