### ISSUE TITLE
Failed Uploading Large Files To Blob Storage

### ISSUE THREAD

**Issue by MarcosxDeveloper** [umbraco/Umbraco.StorageProviders#48] opened 2022-08-10 21:38 UTC
Logs Viewer:

Retry failed after 6 tries. Retry settings can be adjusted in ClientOptions.Retry. (The operation was cancelled because it exceeded the configured timeout of 0:01:40. Network timeout can be adjusted in ClientOptions.Retry.NetworkTimeout.)

**Comment by OwainWilliams** [comment] 2022-09-02 15:25
I've just had this same issue. 
I've a file (Mp4) which is 143Mb which I can upload via the Media Library in the backoffice when running locally. 

As soon as I try and upload the same file via the same method on our deployed website, which is on Azure with Blob storage, I get an error in the console:

![image](https://user-images.githubusercontent.com/9438758/188182317-f4f30b56-e4e1-4cdd-b331-3ca4da1dd453.png)

I can upload the file directly to Blob storage via Azure Storage Explorer with no issues.

**Comment by OwainWilliams** [comment] 2022-09-14 14:59
I've been working on this for the past couple of days and I'm getting a bit further. I can upload files up to 118Mb (takes 5mins) but they do succeed in the end, however, the target file that I need to upload is 143Mb and this fails after 10mins of trying. 

I can upload the file via Azure Storage Explorer with no issues but when I try the same file via the backoffice I eventually get a timeout : 

```
An error occurred
Retry failed after 6 tries. Retry settings can be adjusted in ClientOptions.Retry. (The operation was cancelled because it exceeded the configured timeout of 0:01:40. Network timeout can be adjusted in ClientOptions.Retry.NetworkTimeout.) (The operation was cancelled because it exceeded the configured timeout of 0:01:40. Network timeout can be adjusted in ClientOptions.Retry.NetworkTimeout.) (The operation was cancelled because it exceeded the configured timeout of 0:01:40. Network timeout can be adjusted in ClientOptions.Retry.NetworkTimeout.) (The operation was cancelled because it exceeded the configured timeout of 0:01:40. Network timeout can be adjusted in ClientOptions.Retry.NetworkTimeout.) (The operation was cancelled because it exceeded the configured timeout of 0:01:40. Network timeout can be adjusted in ClientOptions.Retry.NetworkTimeout.) (The operation was cancelled because it exceeded the configured timeout of 0:01:40. Network timeout can be adjusted in ClientOptions.Retry.NetworkTimeout.)

```
I'm not sure if this is something that can be configured within the Storage Provider. 

My next step is to build my own uploader app and test to see if I can successfully upload via that to try and pinpoint why I can't upload large files to blob storage. 

The large file uploads with no issues if I am saving to a local media folder. Blob seems to be the issue.

**Comment by c9mb** [comment] 2022-09-14 23:24
FWIW - I haven't done any work on recent implementations, but on previous versions there was a MaxSize setting on the Azure provider, that managed the maximum size of Blob requests, and this impacted the backoffice when you try to access an uploaded blob - which was quite separate to any website max-size setting. You could actually save files to BlobStorage in the back office but it would then immediately fail when the backoffice tried to display what you just saved.

**Comment by ronaldbarendse** [comment] 2022-10-18 19:28
I've tested this using Umbraco CMS 10.2.0 and Storage Providers 10.0.0 running on my local machine, both using the emulator and a remote Azure Blob Storage container, and 100MB, 1GB, 2GB and 3GB files are uploaded without issues. Uploading to the remote container did take a lot longer compared to local, as it first uploads the file to the application, which then needs to upload to Azure. Running the application remotely will therefore add even more time, as uploading to the application will take longer as well.

I did have to change the maximum upload size of the application though, as per [documentation](https://our.umbraco.com/documentation/Reference/Configuration/MaximumUploadSizeSettings/). If you don't, the default for IIS and Kestrel is around 28.6MB and you'll get an `The page was not displayed because the request entity is too large` error when you go over this limit (as @OwainWilliams encountered first).

The `RetryOptions` shouldn't need adjustment, as that only kicks in when there's connection issues, not when uploading large files (although larger files increase the likelihood of those issues). The Azure Storage Blobs SDK doesn't set a specific maximum blob size at the client side, but this seems to differ [based on the service version of your container](https://learn.microsoft.com/en-us/azure/storage/blobs/scalability-targets#scale-targets-for-blob-storage): can you check what version you're using (check the `sv` parameter in the connection string)?

**Comment by ronaldbarendse** [comment] 2023-07-03 14:26
I'll close this issue because I couldn't replicate it and haven't received additional feedback. Feel free to re-open if this is still an issue on the latest version and you have clear reproduction steps though!

**Closed by ronaldbarendse** 2023-07-03 14:26 UTC
Labels: bug, question
